# General Colours
types:
  Incoming: 0x2ECC71
  Outgoing: 0x3498DB
  Missed: 0xF39C12
  Voicemail: 0x000000
  Rejected: 0xE74C3C
  Blocked: 0x000000
  AnsweredExternally: 0x000000

grid: 0x161F28
background: 0x2C3E50
text: 0xFFFFFF
rollover: 0x9B59B6
expired: 0xFF00FF
default: 0x999999

# Dimensions
size:
  day-width: 40
  sh: 4
  legend-width: 42

# Set as `null` to make date range unbounded
start: 2020-01-01 00:00:00
end: 2021-01-01 00:00:00
start-hour: 6
max-call-length: 9000

# Filtering: Don't include '+1' internation code or hyphens
# true means include, false means exclude, null means allow all
top-callers: 9
show: null
numbers:
  '2065550000': 0xFF9BF5
  '2065551111': 0xF3FF77
