// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calls.proto

public final class Calls {
  private Calls() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Call)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     * @return Whether the start field is set.
     */
    boolean hasStart();
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     * @return The start.
     */
    com.google.protobuf.Timestamp getStart();
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getStartOrBuilder();

    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     * @return Whether the duration field is set.
     */
    boolean hasDuration();
    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     * @return The duration.
     */
    com.google.protobuf.Duration getDuration();
    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     */
    com.google.protobuf.DurationOrBuilder getDurationOrBuilder();

    /**
     * <code>.Call.CallType type = 4;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.Call.CallType type = 4;</code>
     * @return The type.
     */
    Calls.Call.CallType getType();
  }
  /**
   * Protobuf type {@code Call}
   */
  public static final class Call extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Call)
      CallOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Call.newBuilder() to construct.
    private Call(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Call() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Call();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Call(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (start_ != null) {
                subBuilder = start_.toBuilder();
              }
              start_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(start_);
                start_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Duration.Builder subBuilder = null;
              if (duration_ != null) {
                subBuilder = duration_.toBuilder();
              }
              duration_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(duration_);
                duration_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Calls.internal_static_Call_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Calls.internal_static_Call_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Calls.Call.class, Calls.Call.Builder.class);
    }

    /**
     * Protobuf enum {@code Call.CallType}
     */
    public enum CallType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Incoming = 0;</code>
       */
      Incoming(0),
      /**
       * <code>Outgoing = 1;</code>
       */
      Outgoing(1),
      /**
       * <code>Missed = 2;</code>
       */
      Missed(2),
      /**
       * <code>Voicemail = 3;</code>
       */
      Voicemail(3),
      /**
       * <code>Rejected = 4;</code>
       */
      Rejected(4),
      /**
       * <code>Blocked = 5;</code>
       */
      Blocked(5),
      /**
       * <code>AnsweredExternally = 6;</code>
       */
      AnsweredExternally(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Incoming = 0;</code>
       */
      public static final int Incoming_VALUE = 0;
      /**
       * <code>Outgoing = 1;</code>
       */
      public static final int Outgoing_VALUE = 1;
      /**
       * <code>Missed = 2;</code>
       */
      public static final int Missed_VALUE = 2;
      /**
       * <code>Voicemail = 3;</code>
       */
      public static final int Voicemail_VALUE = 3;
      /**
       * <code>Rejected = 4;</code>
       */
      public static final int Rejected_VALUE = 4;
      /**
       * <code>Blocked = 5;</code>
       */
      public static final int Blocked_VALUE = 5;
      /**
       * <code>AnsweredExternally = 6;</code>
       */
      public static final int AnsweredExternally_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CallType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CallType forNumber(int value) {
        switch (value) {
          case 0: return Incoming;
          case 1: return Outgoing;
          case 2: return Missed;
          case 3: return Voicemail;
          case 4: return Rejected;
          case 5: return Blocked;
          case 6: return AnsweredExternally;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CallType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CallType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CallType>() {
              public CallType findValueByNumber(int number) {
                return CallType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Calls.Call.getDescriptor().getEnumTypes().get(0);
      }

      private static final CallType[] VALUES = values();

      public static CallType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CallType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Call.CallType)
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp start_;
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return start_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     * @return The start.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getStart() {
      return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
      return getStart();
    }

    public static final int DURATION_FIELD_NUMBER = 3;
    private com.google.protobuf.Duration duration_;
    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     * @return Whether the duration field is set.
     */
    @java.lang.Override
    public boolean hasDuration() {
      return duration_ != null;
    }
    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     * @return The duration.
     */
    @java.lang.Override
    public com.google.protobuf.Duration getDuration() {
      return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
    }
    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
      return getDuration();
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>.Call.CallType type = 4;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Call.CallType type = 4;</code>
     * @return The type.
     */
    @java.lang.Override public Calls.Call.CallType getType() {
      @SuppressWarnings("deprecation")
      Calls.Call.CallType result = Calls.Call.CallType.valueOf(type_);
      return result == null ? Calls.Call.CallType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (start_ != null) {
        output.writeMessage(2, getStart());
      }
      if (duration_ != null) {
        output.writeMessage(3, getDuration());
      }
      if (type_ != Calls.Call.CallType.Incoming.getNumber()) {
        output.writeEnum(4, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (start_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStart());
      }
      if (duration_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDuration());
      }
      if (type_ != Calls.Call.CallType.Incoming.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Calls.Call)) {
        return super.equals(obj);
      }
      Calls.Call other = (Calls.Call) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (hasStart() != other.hasStart()) return false;
      if (hasStart()) {
        if (!getStart()
            .equals(other.getStart())) return false;
      }
      if (hasDuration() != other.hasDuration()) return false;
      if (hasDuration()) {
        if (!getDuration()
            .equals(other.getDuration())) return false;
      }
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (hasDuration()) {
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDuration().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Calls.Call parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calls.Call parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calls.Call parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calls.Call parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calls.Call parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calls.Call parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calls.Call parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Calls.Call parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Calls.Call parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Calls.Call parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Calls.Call parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Calls.Call parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Calls.Call prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Call}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Call)
        Calls.CallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Calls.internal_static_Call_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Calls.internal_static_Call_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Calls.Call.class, Calls.Call.Builder.class);
      }

      // Construct using Calls.Call.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";

        if (startBuilder_ == null) {
          start_ = null;
        } else {
          start_ = null;
          startBuilder_ = null;
        }
        if (durationBuilder_ == null) {
          duration_ = null;
        } else {
          duration_ = null;
          durationBuilder_ = null;
        }
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Calls.internal_static_Call_descriptor;
      }

      @java.lang.Override
      public Calls.Call getDefaultInstanceForType() {
        return Calls.Call.getDefaultInstance();
      }

      @java.lang.Override
      public Calls.Call build() {
        Calls.Call result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Calls.Call buildPartial() {
        Calls.Call result = new Calls.Call(this);
        result.number_ = number_;
        if (startBuilder_ == null) {
          result.start_ = start_;
        } else {
          result.start_ = startBuilder_.build();
        }
        if (durationBuilder_ == null) {
          result.duration_ = duration_;
        } else {
          result.duration_ = durationBuilder_.build();
        }
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Calls.Call) {
          return mergeFrom((Calls.Call)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Calls.Call other) {
        if (other == Calls.Call.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (other.hasStart()) {
          mergeStart(other.getStart());
        }
        if (other.hasDuration()) {
          mergeDuration(other.getDuration());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Calls.Call parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Calls.Call) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp start_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startBuilder_;
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       * @return Whether the start field is set.
       */
      public boolean hasStart() {
        return startBuilder_ != null || start_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       * @return The start.
       */
      public com.google.protobuf.Timestamp getStart() {
        if (startBuilder_ == null) {
          return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
        } else {
          return startBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder setStart(com.google.protobuf.Timestamp value) {
        if (startBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          start_ = value;
          onChanged();
        } else {
          startBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder setStart(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (startBuilder_ == null) {
          start_ = builderForValue.build();
          onChanged();
        } else {
          startBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder mergeStart(com.google.protobuf.Timestamp value) {
        if (startBuilder_ == null) {
          if (start_ != null) {
            start_ =
              com.google.protobuf.Timestamp.newBuilder(start_).mergeFrom(value).buildPartial();
          } else {
            start_ = value;
          }
          onChanged();
        } else {
          startBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public Builder clearStart() {
        if (startBuilder_ == null) {
          start_ = null;
          onChanged();
        } else {
          start_ = null;
          startBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getStartBuilder() {
        
        onChanged();
        return getStartFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
        if (startBuilder_ != null) {
          return startBuilder_.getMessageOrBuilder();
        } else {
          return start_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : start_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp start = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStartFieldBuilder() {
        if (startBuilder_ == null) {
          startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStart(),
                  getParentForChildren(),
                  isClean());
          start_ = null;
        }
        return startBuilder_;
      }

      private com.google.protobuf.Duration duration_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationBuilder_;
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       * @return Whether the duration field is set.
       */
      public boolean hasDuration() {
        return durationBuilder_ != null || duration_ != null;
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       * @return The duration.
       */
      public com.google.protobuf.Duration getDuration() {
        if (durationBuilder_ == null) {
          return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
        } else {
          return durationBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       */
      public Builder setDuration(com.google.protobuf.Duration value) {
        if (durationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          duration_ = value;
          onChanged();
        } else {
          durationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       */
      public Builder setDuration(
          com.google.protobuf.Duration.Builder builderForValue) {
        if (durationBuilder_ == null) {
          duration_ = builderForValue.build();
          onChanged();
        } else {
          durationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       */
      public Builder mergeDuration(com.google.protobuf.Duration value) {
        if (durationBuilder_ == null) {
          if (duration_ != null) {
            duration_ =
              com.google.protobuf.Duration.newBuilder(duration_).mergeFrom(value).buildPartial();
          } else {
            duration_ = value;
          }
          onChanged();
        } else {
          durationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       */
      public Builder clearDuration() {
        if (durationBuilder_ == null) {
          duration_ = null;
          onChanged();
        } else {
          duration_ = null;
          durationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       */
      public com.google.protobuf.Duration.Builder getDurationBuilder() {
        
        onChanged();
        return getDurationFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       */
      public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
        if (durationBuilder_ != null) {
          return durationBuilder_.getMessageOrBuilder();
        } else {
          return duration_ == null ?
              com.google.protobuf.Duration.getDefaultInstance() : duration_;
        }
      }
      /**
       * <code>.google.protobuf.Duration duration = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
          getDurationFieldBuilder() {
        if (durationBuilder_ == null) {
          durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                  getDuration(),
                  getParentForChildren(),
                  isClean());
          duration_ = null;
        }
        return durationBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>.Call.CallType type = 4;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Call.CallType type = 4;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Call.CallType type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public Calls.Call.CallType getType() {
        @SuppressWarnings("deprecation")
        Calls.Call.CallType result = Calls.Call.CallType.valueOf(type_);
        return result == null ? Calls.Call.CallType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Call.CallType type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(Calls.Call.CallType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Call.CallType type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Call)
    }

    // @@protoc_insertion_point(class_scope:Call)
    private static final Calls.Call DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Calls.Call();
    }

    public static Calls.Call getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Call>
        PARSER = new com.google.protobuf.AbstractParser<Call>() {
      @java.lang.Override
      public Call parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Call(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Call> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Call> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Calls.Call getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CallHistoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CallHistory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Call calls = 1;</code>
     */
    java.util.List<Calls.Call> 
        getCallsList();
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    Calls.Call getCalls(int index);
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    int getCallsCount();
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    java.util.List<? extends Calls.CallOrBuilder> 
        getCallsOrBuilderList();
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    Calls.CallOrBuilder getCallsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CallHistory}
   */
  public static final class CallHistory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CallHistory)
      CallHistoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CallHistory.newBuilder() to construct.
    private CallHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallHistory() {
      calls_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CallHistory();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallHistory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                calls_ = new java.util.ArrayList<Calls.Call>();
                mutable_bitField0_ |= 0x00000001;
              }
              calls_.add(
                  input.readMessage(Calls.Call.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          calls_ = java.util.Collections.unmodifiableList(calls_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Calls.internal_static_CallHistory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Calls.internal_static_CallHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Calls.CallHistory.class, Calls.CallHistory.Builder.class);
    }

    public static final int CALLS_FIELD_NUMBER = 1;
    private java.util.List<Calls.Call> calls_;
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Calls.Call> getCallsList() {
      return calls_;
    }
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Calls.CallOrBuilder> 
        getCallsOrBuilderList() {
      return calls_;
    }
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    @java.lang.Override
    public int getCallsCount() {
      return calls_.size();
    }
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    @java.lang.Override
    public Calls.Call getCalls(int index) {
      return calls_.get(index);
    }
    /**
     * <code>repeated .Call calls = 1;</code>
     */
    @java.lang.Override
    public Calls.CallOrBuilder getCallsOrBuilder(
        int index) {
      return calls_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < calls_.size(); i++) {
        output.writeMessage(1, calls_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < calls_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, calls_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Calls.CallHistory)) {
        return super.equals(obj);
      }
      Calls.CallHistory other = (Calls.CallHistory) obj;

      if (!getCallsList()
          .equals(other.getCallsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCallsCount() > 0) {
        hash = (37 * hash) + CALLS_FIELD_NUMBER;
        hash = (53 * hash) + getCallsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Calls.CallHistory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calls.CallHistory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calls.CallHistory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calls.CallHistory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calls.CallHistory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Calls.CallHistory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Calls.CallHistory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Calls.CallHistory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Calls.CallHistory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Calls.CallHistory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Calls.CallHistory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Calls.CallHistory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Calls.CallHistory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CallHistory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CallHistory)
        Calls.CallHistoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Calls.internal_static_CallHistory_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Calls.internal_static_CallHistory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Calls.CallHistory.class, Calls.CallHistory.Builder.class);
      }

      // Construct using Calls.CallHistory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCallsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (callsBuilder_ == null) {
          calls_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          callsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Calls.internal_static_CallHistory_descriptor;
      }

      @java.lang.Override
      public Calls.CallHistory getDefaultInstanceForType() {
        return Calls.CallHistory.getDefaultInstance();
      }

      @java.lang.Override
      public Calls.CallHistory build() {
        Calls.CallHistory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Calls.CallHistory buildPartial() {
        Calls.CallHistory result = new Calls.CallHistory(this);
        int from_bitField0_ = bitField0_;
        if (callsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            calls_ = java.util.Collections.unmodifiableList(calls_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.calls_ = calls_;
        } else {
          result.calls_ = callsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Calls.CallHistory) {
          return mergeFrom((Calls.CallHistory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Calls.CallHistory other) {
        if (other == Calls.CallHistory.getDefaultInstance()) return this;
        if (callsBuilder_ == null) {
          if (!other.calls_.isEmpty()) {
            if (calls_.isEmpty()) {
              calls_ = other.calls_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCallsIsMutable();
              calls_.addAll(other.calls_);
            }
            onChanged();
          }
        } else {
          if (!other.calls_.isEmpty()) {
            if (callsBuilder_.isEmpty()) {
              callsBuilder_.dispose();
              callsBuilder_ = null;
              calls_ = other.calls_;
              bitField0_ = (bitField0_ & ~0x00000001);
              callsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCallsFieldBuilder() : null;
            } else {
              callsBuilder_.addAllMessages(other.calls_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Calls.CallHistory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Calls.CallHistory) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Calls.Call> calls_ =
        java.util.Collections.emptyList();
      private void ensureCallsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          calls_ = new java.util.ArrayList<Calls.Call>(calls_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Calls.Call, Calls.Call.Builder, Calls.CallOrBuilder> callsBuilder_;

      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public java.util.List<Calls.Call> getCallsList() {
        if (callsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(calls_);
        } else {
          return callsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public int getCallsCount() {
        if (callsBuilder_ == null) {
          return calls_.size();
        } else {
          return callsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Calls.Call getCalls(int index) {
        if (callsBuilder_ == null) {
          return calls_.get(index);
        } else {
          return callsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder setCalls(
          int index, Calls.Call value) {
        if (callsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsIsMutable();
          calls_.set(index, value);
          onChanged();
        } else {
          callsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder setCalls(
          int index, Calls.Call.Builder builderForValue) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.set(index, builderForValue.build());
          onChanged();
        } else {
          callsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder addCalls(Calls.Call value) {
        if (callsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsIsMutable();
          calls_.add(value);
          onChanged();
        } else {
          callsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder addCalls(
          int index, Calls.Call value) {
        if (callsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCallsIsMutable();
          calls_.add(index, value);
          onChanged();
        } else {
          callsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder addCalls(
          Calls.Call.Builder builderForValue) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.add(builderForValue.build());
          onChanged();
        } else {
          callsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder addCalls(
          int index, Calls.Call.Builder builderForValue) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.add(index, builderForValue.build());
          onChanged();
        } else {
          callsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder addAllCalls(
          java.lang.Iterable<? extends Calls.Call> values) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, calls_);
          onChanged();
        } else {
          callsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder clearCalls() {
        if (callsBuilder_ == null) {
          calls_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          callsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Builder removeCalls(int index) {
        if (callsBuilder_ == null) {
          ensureCallsIsMutable();
          calls_.remove(index);
          onChanged();
        } else {
          callsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Calls.Call.Builder getCallsBuilder(
          int index) {
        return getCallsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Calls.CallOrBuilder getCallsOrBuilder(
          int index) {
        if (callsBuilder_ == null) {
          return calls_.get(index);  } else {
          return callsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public java.util.List<? extends Calls.CallOrBuilder> 
           getCallsOrBuilderList() {
        if (callsBuilder_ != null) {
          return callsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(calls_);
        }
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Calls.Call.Builder addCallsBuilder() {
        return getCallsFieldBuilder().addBuilder(
            Calls.Call.getDefaultInstance());
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public Calls.Call.Builder addCallsBuilder(
          int index) {
        return getCallsFieldBuilder().addBuilder(
            index, Calls.Call.getDefaultInstance());
      }
      /**
       * <code>repeated .Call calls = 1;</code>
       */
      public java.util.List<Calls.Call.Builder> 
           getCallsBuilderList() {
        return getCallsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Calls.Call, Calls.Call.Builder, Calls.CallOrBuilder> 
          getCallsFieldBuilder() {
        if (callsBuilder_ == null) {
          callsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Calls.Call, Calls.Call.Builder, Calls.CallOrBuilder>(
                  calls_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          calls_ = null;
        }
        return callsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CallHistory)
    }

    // @@protoc_insertion_point(class_scope:CallHistory)
    private static final Calls.CallHistory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Calls.CallHistory();
    }

    public static Calls.CallHistory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallHistory>
        PARSER = new com.google.protobuf.AbstractParser<CallHistory>() {
      @java.lang.Override
      public CallHistory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CallHistory(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallHistory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CallHistory> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Calls.CallHistory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Call_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Call_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallHistory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallHistory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013calls.proto\032\036google/protobuf/duration." +
      "proto\032\037google/protobuf/timestamp.proto\"\202" +
      "\002\n\004Call\022\016\n\006number\030\001 \001(\t\022)\n\005start\030\002 \001(\0132\032" +
      ".google.protobuf.Timestamp\022+\n\010duration\030\003" +
      " \001(\0132\031.google.protobuf.Duration\022\034\n\004type\030" +
      "\004 \001(\0162\016.Call.CallType\"t\n\010CallType\022\014\n\010Inc" +
      "oming\020\000\022\014\n\010Outgoing\020\001\022\n\n\006Missed\020\002\022\r\n\tVoi" +
      "cemail\020\003\022\014\n\010Rejected\020\004\022\013\n\007Blocked\020\005\022\026\n\022A" +
      "nsweredExternally\020\006\"#\n\013CallHistory\022\024\n\005ca" +
      "lls\030\001 \003(\0132\005.Callb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Call_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Call_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Call_descriptor,
        new java.lang.String[] { "Number", "Start", "Duration", "Type", });
    internal_static_CallHistory_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CallHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallHistory_descriptor,
        new java.lang.String[] { "Calls", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
