//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calls.proto

@kotlin.jvm.JvmSynthetic
public inline fun callHistory(block: CallHistoryKt.Dsl.() -> kotlin.Unit): Calls.CallHistory =
  CallHistoryKt.Dsl._create(Calls.CallHistory.newBuilder()).apply { block() }._build()
public object CallHistoryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Calls.CallHistory.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Calls.CallHistory.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Calls.CallHistory = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CallsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .Call calls = 1;</code>
     */
     public val calls: com.google.protobuf.kotlin.DslList<Calls.Call, CallsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getCallsList()
      )
    /**
     * <code>repeated .Call calls = 1;</code>
     * @param value The calls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCalls")
    public fun com.google.protobuf.kotlin.DslList<Calls.Call, CallsProxy>.add(value: Calls.Call) {
      _builder.addCalls(value)
    }/**
     * <code>repeated .Call calls = 1;</code>
     * @param value The calls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCalls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Calls.Call, CallsProxy>.plusAssign(value: Calls.Call) {
      add(value)
    }/**
     * <code>repeated .Call calls = 1;</code>
     * @param values The calls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCalls")
    public fun com.google.protobuf.kotlin.DslList<Calls.Call, CallsProxy>.addAll(values: kotlin.collections.Iterable<Calls.Call>) {
      _builder.addAllCalls(values)
    }/**
     * <code>repeated .Call calls = 1;</code>
     * @param values The calls to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCalls")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Calls.Call, CallsProxy>.plusAssign(values: kotlin.collections.Iterable<Calls.Call>) {
      addAll(values)
    }/**
     * <code>repeated .Call calls = 1;</code>
     * @param index The index to set the value at.
     * @param value The calls to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCalls")
    public operator fun com.google.protobuf.kotlin.DslList<Calls.Call, CallsProxy>.set(index: kotlin.Int, value: Calls.Call) {
      _builder.setCalls(index, value)
    }/**
     * <code>repeated .Call calls = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCalls")
    public fun com.google.protobuf.kotlin.DslList<Calls.Call, CallsProxy>.clear() {
      _builder.clearCalls()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun Calls.CallHistory.copy(block: CallHistoryKt.Dsl.() -> kotlin.Unit): Calls.CallHistory =
  CallHistoryKt.Dsl._create(this.toBuilder()).apply { block() }._build()
