//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: calls.proto

@kotlin.jvm.JvmSynthetic
public inline fun call(block: CallKt.Dsl.() -> kotlin.Unit): Calls.Call =
  CallKt.Dsl._create(Calls.Call.newBuilder()).apply { block() }._build()
public object CallKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Calls.Call.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Calls.Call.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Calls.Call = _builder.build()

    /**
     * <code>string number = 1;</code>
     */
    public var number: kotlin.String
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * <code>string number = 1;</code>
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }

    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public var start: com.google.protobuf.Timestamp
      @JvmName("getStart")
      get() = _builder.getStart()
      @JvmName("setStart")
      set(value) {
        _builder.setStart(value)
      }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public fun clearStart() {
      _builder.clearStart()
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     * @return Whether the start field is set.
     */
    public fun hasStart(): kotlin.Boolean {
      return _builder.hasStart()
    }

    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     */
    public var duration: com.google.protobuf.Duration
      @JvmName("getDuration")
      get() = _builder.getDuration()
      @JvmName("setDuration")
      set(value) {
        _builder.setDuration(value)
      }
    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }
    /**
     * <code>.google.protobuf.Duration duration = 3;</code>
     * @return Whether the duration field is set.
     */
    public fun hasDuration(): kotlin.Boolean {
      return _builder.hasDuration()
    }

    /**
     * <code>.Call.CallType type = 4;</code>
     */
    public var type: Calls.Call.CallType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>.Call.CallType type = 4;</code>
     */
    public fun clearType() {
      _builder.clearType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Calls.Call.copy(block: CallKt.Dsl.() -> kotlin.Unit): Calls.Call =
  CallKt.Dsl._create(this.toBuilder()).apply { block() }._build()
